# Generated by Django 4.2.27 on 2025-12-27 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0002_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_upload_csv', 'Can upload CSV'), ('can_view_teacher', 'Can view teacher analytics'), ('can_view_department', 'Can view department analytics')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherUserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Привязка преподавателя к пользователю',
                'verbose_name_plural': 'Привязки преподавателей к пользователям',
            },
        ),
        migrations.RemoveField(
            model_name='result',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='result',
            name='attendance_percent',
            field=models.FloatField(default=0, verbose_name='Посещаемость (%)'),
        ),
        migrations.AlterField(
            model_name='result',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analytics.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='result',
            name='grade',
            field=models.FloatField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='result',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analytics.semester', verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analytics.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='result',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='analytics.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('student', 'discipline', 'teacher', 'semester'), name='uniq_result_student_discipline_teacher_semester'),
        ),
        migrations.AddField(
            model_name='teacheruserlink',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='analytics.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='teacheruserlink',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_link', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
