# Generated by ChatGPT on 2025-12-28

from django.db import migrations


def seed_roles_and_users(apps, schema_editor):
    """Создаём группы, права и демонстрационные учётки.

    Это решает проблему, когда проверяющий запускает проект «с нуля»
    и не может войти под ролями "Преподаватель" / "Руководитель кафедры".
    """

    Group = apps.get_model("auth", "Group")
    User = apps.get_model("auth", "User")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # Группы
    g_teacher, _ = Group.objects.get_or_create(name="Преподаватель")
    g_head, _ = Group.objects.get_or_create(name="Руководитель кафедры")
    Group.objects.get_or_create(name="Руководитель")
    Group.objects.get_or_create(name="Администратор")

    # Права (они объявлены в RolePermissions (managed=False),
    # поэтому объект ContentType для приложения analytics нужен, чтобы их найти.)
    ct, _ = ContentType.objects.get_or_create(app_label="analytics", model="rolepermissions")

    def perm(codename):
        return Permission.objects.filter(content_type=ct, codename=codename).first()

    p_upload = perm("can_upload_csv")
    p_view_teacher = perm("can_view_teacher")
    p_view_dept = perm("can_view_department")

    # Назначаем права группам (если права существуют)
    if p_view_teacher:
        g_teacher.permissions.add(p_view_teacher)
    if p_upload:
        g_head.permissions.add(p_upload)
    if p_view_dept:
        g_head.permissions.add(p_view_dept)

    # Демонстрационные пользователи
    # Пароль: demo12345 (можно поменять в README)
    demo_password = "demo12345"

    def ensure_user(username, first_name, last_name, group_obj):
        u = User.objects.filter(username=username).first()
        if not u:
            u = User(username=username, first_name=first_name, last_name=last_name, is_active=True)
            # set_password доступен у модели User (even through historical model)
            u.set_password(demo_password)
            u.save()
        u.groups.add(group_obj)
        return u

    ensure_user("teacher", "Иван", "Преподаватель", g_teacher)
    ensure_user("head", "Мария", "Руководитель", g_head)


def unseed(apps, schema_editor):
    # Откат: удаляем только демо-пользователей, группы оставляем.
    User = apps.get_model("auth", "User")
    User.objects.filter(username__in=["teacher", "head"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_rolepermissions_teacheruserlink_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_roles_and_users, unseed),
    ]
